### ISSUE TITLE
glad to see mqtt in rust.

### ISSUE THREAD

**Issue by lerencao** [zonyitoo/mqtt-rs#1]
I am interested in mqtt recently. It's very lucky to see this, especially in rust.
I am still learning, but would like to do some contribution here.

**Comment by zonyitoo** [comment]
That's great!

**Comment by kteza1** [comment]
Do you think this can be used for production yet?

**Comment by zonyitoo** [comment]
@kteza1 I don't know, I haven't tried yet.

**Comment by zonyitoo** [comment]
Close because of inactivity
