### ISSUE TITLE
UnsubscribePacketPayload should be Vec<TopicFilter> ?

### ISSUE THREAD

**Issue by TheWaWaR** [zonyitoo/mqtt-rs#10]
http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718075
As the protocol says:
>  The payload for the UNSUBSCRIBE Packet contains the list of Topic Filters that the Client wishes to unsubscribe from

But, in your code:
``` rust
pub struct UnsubscribePacketPayload {
    subscribes: Vec<String>,
}
```

**Comment by zonyitoo** [comment]
Hmmm ... well, I think you are right. You could submit a PR for this if you want to, because I dont have time to update it these days

**Comment by zonyitoo** [comment]
Already fixed. Closing.
