### ISSUE TITLE
[Bug] Connect package's will message should be encoded with length

### ISSUE THREAD

**Issue by zonyitoo** [zonyitoo/mqtt-rs#14]
According to the [specification](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc385349244), 

> This field consists of a two byte length followed by the payload for the Will Message expressed as a sequence of zero or more bytes. The length gives the number of bytes in the data that follows and does not include the 2 bytes taken up by the length itself.

cc @rschifflin, #13

**Comment by zonyitoo** [comment]
Please @rschifflin check out the latest commit and see if it works well in your project.

**Comment by rschifflin** [comment]
@zonyitoo tested it on my end, this works perfectly- binary last will is valid in the connect packet and binary messages are sent/received intact. Thanks!

**Comment by zonyitoo** [comment]
Will be published as `v0.3.1`
