### ISSUE TITLE
Slash is not allowed in topic name

### ISSUE THREAD

**Issue by Albibek** [zonyitoo/mqtt-rs#16]
Hi.

The standard's [4.7.1.1](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718106) says: 

> Topic level separators can appear anywhere in a Topic Filter or Topic Name

But the regexp doesn't allow it and `TopicName::new` fails.

Also the regexps for `TopicName` and `TopicFilter` could be compiled only once using [lazy_static!](https://doc.rust-lang.org/regex/regex/index.html#example-avoid-compiling-the-same-regex-in-a-loop) to avoid compiling them each time strings are compared.

**Comment by zonyitoo** [comment]
@Albibek Please check the latest commit. :)

**Comment by Albibek** [comment]
Works for me. Thanks!

**Comment by zonyitoo** [comment]
Published `v0.4.0`
