### ISSUE TITLE
TopicName and TopicFilter should provide some way of accessing the internal String 

### ISSUE THREAD

**Issue by jeff-at-dwelo** [zonyitoo/mqtt-rs#29]
This one bit me while trying to write a mock server, and trying to construct a fake PublishPacket given a SubscribePacket. I was going to extract the underlying String, replace any wildcard characters with mock strings, create a new TopicName from that, and then issue a Publish. But there doesn't seem to be any way to access the owned String.

Basically I need a `get_str(&self)` method or something similar on TopicFilter that returns a `&str`. For symmetry we should also provide an accessor for TopicName's String. Does this approach sound OK to you?

**Comment by zonyitoo** [comment]
Or maybe `get_ref`, `into_inner`? Following the naming style of libstd.

**Comment by jeff-at-dwelo** [comment]
Hilariously, I just had the same thought waking up this morning. I was also wondering about the purpose of `TopicNameRef` and `TopicFilterRef`, and the impl of `Deref`; was that intended to provide access to the inner String? If so it wasn't clear to me how to do so, though I'm still a bit new at Rust.

I think if we do implement `get_ref` and `into_inner` we should probably get rid of these to simplify the code, though it would require bumping the version to 0.7.0.

**Comment by zonyitoo** [comment]
https://github.com/zonyitoo/mqtt-rs/blob/master/src/topic_name.rs#L150

Well, `TopicNameRef` and `TopicFilterRef` are wrapper types, which allows me to implement member functions for them. (I cannot implement any helper functions for `str`!)

**Comment by jeff-at-dwelo** [comment]
Ah, so those are basically just wrappers for non-owned &str and its RefAs equivalents? Trying to wrap my head around it. I'll see if I can get the String out from the non-ref via a Deref coercion, and if I can easily do so then I'll close this out.  Otherwise I'll PR for comment.

**Comment by jeff-at-dwelo** [comment]
Huh. OK, I was mistaken, it looks like I can just run `.as_ref()` with a turbofish and get `&str` out of a TopicFilter. So, problem solved for me!

Closing this out, I've got no further issues. Any chance we can get a 0.6.1 release for the other two recent PRs?

**Comment by zonyitoo** [comment]
Published. BTW, you can use `&**x` to get `&str` type. Just try it.
