### ISSUE TITLE
Unable to decode disconnect packet

### ISSUE THREAD

**Issue by kteza1** [zonyitoo/mqtt-rs#4]
I've added `conn.set_keep_alive(5);` to `sub-client` example and broker is disconnecting as expected if there is no message exchange within `keep_alive` time

```
1458943648: Client /MQTT/rust/e2603b7b64714a2bb198a054c08e9f68 has exceeded timeout, disconnecting.
```
I expect broker to be sending disconnect packet at this point and to verify this I added below lines in the [2nd loop](https://github.com/zonyitoo/mqtt-rs/blob/master/examples/sub-client.rs#L123)
```
&VariablePacket::DisconnectPacket(..) => {
                error!("Received disconnect packet from broker");
                break;
            }
```

But unfortunately, this condition isn't getting hit and I'm stuck with infinite loop of below error [here](https://github.com/zonyitoo/mqtt-rs/blob/master/examples/sub-client.rs#L126-L129)

```
ERROR:sub_client: Error in receiving packet unexpected EOF
ERROR:sub_client: Error in receiving packet unexpected EOF
ERROR:sub_client: Error in receiving packet unexpected EOF
```

**Comment by zonyitoo** [comment]
The error is "unexpected EOF", which means that the server is already disconnected and the socket is already been closed. So the `VariablePacket::decode` returns error "unexpected EOF".

I don't know where exactly the error is thrown from, you should modify `{}` in [here](https://github.com/zonyitoo/mqtt-rs/blob/master/examples/sub-client.rs#L127) to be `{:?}` and check the exact structure. But alternatively, you could also just `break` if you received an `err` from `decode`.

**Comment by zonyitoo** [comment]
Here is a test case:

```rust
extern crate mqtt;

use std::io::Cursor;

use mqtt::{Encodable, Decodable};
use mqtt::packet::*;

fn main() {
    let d = DisconnectPacket::new();
    let mut buf = Vec::new();
    d.encode(&mut buf).unwrap();

    println!("Encoded: {:?}", buf);

    let mut dec_buf = Cursor::new(&buf[..]);
    let auto_decode = VariablePacket::decode(&mut dec_buf).unwrap();
    println!("Variable packet decode: {:?}", auto_decode);
}
```

It should prints:

```
Encoded: [224, 0]
Variable packet decode: DisconnectPacket(DisconnectPacket { fixed_header: FixedHeader { packet_type: PacketType { control_type: Disconnect, flags: 0 }, remaining_length: 0 }, payload: () })
```

which means that both encoding and decoding works well for `DisconnectPacket` and `VariablePacket` for `DISCONNECT`.

So the problem should be: after the server sent the `DISCONNECT` packet, it shutdown immediately, so when you read it, unfortunately the socket is already been closed, so you got an EOF error.

**Comment by zonyitoo** [comment]
Close because of inactivity
