### ISSUE TITLE
Example with server

### ISSUE THREAD

**Issue by Lawliet-Chan** [zonyitoo/mqtt-rs#40]
I think you can write an example code about TCP server. 
Thanks a lot.

**Comment by zonyitoo** [comment]
It shouldn't have any diffenence between client and server in protocol level.

**Comment by Lawliet-Chan** [comment]
I mean that you can use mqtt-rs to write codes about tcp server  for developers. Now the examples just include tcp client.

**Comment by Bobbbay** [comment]
Hi,

Bump -- it's been over a year and this is still needed. Just a basic example of how to create a server (probably via TcpListener) using mqtt-rs. Cheers!
