### ISSUE TITLE
Add support for non-blocking sockets

### ISSUE THREAD

**Issue by Spoonbender** [zonyitoo/mqtt-rs#41]
Currently mqtt-rs doesn't handle non-blocking sockets properly - it doesn't provide any special handling for IO errors where `ErrorKind == WouldBlock` (or `Interrupted`)), even though such errors are part of the `std::io::Read` and `std::io::Write` APIs. 

I work around this issue by setting my own buffers between mqtt-rs and the actual network socket, so mqtt-rs always decodes from and encodes to the in-memory buffers, and the network I/O is handled externally.

Adding support for non-blocking sockets would be non-trivial, but a very welcomed feature.

**Comment by zonyitoo** [comment]
There may be another way, wraps your sockets with `Feature`s, and use it with the async APIs.

**Comment by Spoonbender** [comment]
@zonyitoo correct, but some use-cases don't permit futures / tokio etc., which is why I'm asking you to consider this feature.
You can find an example of support for non-blocking sockets in the `native_tls` crate: https://github.com/sfackler/rust-native-tls/blob/9a9e79825cde4705bad1b2192962066e29d365b5/src/imp/openssl.rs#L233 (and I can also share my code if that helps)

**Comment by zonyitoo** [comment]
Sure, it will help.

**Comment by Spoonbender** [comment]
Actually after giving this some more thought, it would be quite difficult to implement this at the `mqtt-rs` library: we'd need an operation such as `try_decode` which may return an error, or a decoded packet, or a "packet in mid-decoding state". The assumption that reads are blocking greatly simplifies the `mqtt-rs` code.

To simplify: my application creates a non-blocking socket (connected to an MQTT broker), and performs this kind of loop:
1.  Fetch whatever bytes are ready for reading from the socket (if any) and put them in the buffer
2. Attempt to decode an MQTT packet from the buffer (`get_next_packet()`), by examining the FixedHeader and the buffer's data length and deducing if the entire packet has arrived into the buffer. 
3. If we have a (whole) packet at hand - process it.
4. Go do other things
5. Repeat

Here is my code that uses `mqtt-rs` to decode MQTT packets from a buffer.
`self.buffer` points ay my implementation of a circular buffer, but it could be any buffer really.

```rust
pub struct MqttPacketizer {
    buffer: CircularBuffer,
}

impl MqttPacketizer {
   /// snipped other functions

    /// Attempts to decode the next MQTT packet from the buffer
    ///
    /// # Errors
    /// - Returns InvalidData if the decoded MQTT packet is invalid, or in case the packet being assembled is bigger than the total capacity of the buffer, which means we'll never be able to decode it.
    pub fn get_next_packet(&mut self) -> Result<Option<VariablePacket>, std::io::Error> {
        if self.buffer.valid_length() <= 1 {
            // not enough bytes for a fixed header (minimum is 2), wait for more bytes
            return Ok(None);
        }

        // The MQTT fixed header is actually not "fixed size": its size is between 2 and 5 bytes
        let max_fixed_header_bytes = std::cmp::min(self.buffer.valid_length(), 5);
        let mut fixed_header_bytes = self.buffer.peek(max_fixed_header_bytes);
        match FixedHeader::decode(&mut fixed_header_bytes) {
            Ok(fixed_header) => {
                let fixed_header_length = fixed_header.encoded_length();
                let packet_length = (fixed_header_length + fixed_header.remaining_length) as usize;
                if self.buffer.valid_length() < packet_length {
                    // not all packet bytes arrived
                    if self.buffer.size() < packet_length {
                        // the packet is bigger than the buffer size, and will never fit in.
                        warn!(
                            "Packet size exeeds buffer size. Packet size: {}, buffer size: {}",
                            packet_length,
                            self.buffer.size()
                        );
                        return Err(ErrorKind::InvalidData.into());
                    }
                    // wait for more bytes to arrive...
                    return Ok(None);
                }

                let mut packet_bytes = self.buffer.read_bytes(packet_length);
                let packet = match VariablePacket::decode(&mut packet_bytes) {
                    Ok(packet) => packet,
                    Err(e) => match e {
                        VariablePacketError::IoError(ioe) => return Err(ioe),
                        _other => return Err(ErrorKind::InvalidData.into()),
                    },
                };
                Ok(Some(packet))
            }
            Err(FixedHeaderError::IoError(ioe)) if ioe.kind() == ErrorKind::UnexpectedEof => {
                // Fixed header is incomplete, wait for more bytes, meanwhile we don't have a packet to return...
                Ok(None)
            }
            Err(_e) => Err(ErrorKind::InvalidData.into()),
        }
    }
}
```

**Comment by zonyitoo** [comment]
Hmm, well, currently `decode` accepts an `io::Read` object. So you could just simply wrap your `self.buffer` with a `io::Cursor`.

If we can always return a `ErrorKind::UnexpectedEof` if buffer is too short, then it should works, right?

**Comment by Spoonbender** [comment]
> Hmm, well, currently `decode` accepts an `io::Read` object. So you could just simply wrap your `self.buffer` with a `io::Cursor`.
> 
> If we can always return a `ErrorKind::UnexpectedEof` if buffer is too short, then it should works, right?

1. I think that is a start, but I don't think that would be enough: we need to somehow distinguish the case where the buffer doesn't contain the entire packet yet, and the case where the packet is bigger than the buffer (and will never fit in).

2. It would be somewhat inefficient. Say we're decoding a PUBLISH packet, and the fixed header arrived already to the buffer, but not all of the payload arrived yet. Each attempt to `decode` will allocate a new `Vec<u8>` with the capacity of the payload (happens inside `Vec::<u8>::decode_with()`), just to throw it away a moment later. 

As far as I'm concerned, we can close this issue for now - I think that efficiently supporting non-blocking sockets inside `mqtt-rs` is probably too big of a change for the time being. 🤷🏼‍♂️
