### ISSUE TITLE
suggestion to improve readability of enum QualityOfService 

### ISSUE THREAD

**Issue by goutham2688** [zonyitoo/mqtt-rs#55]
Can the enum QualityOfService  be updated as like below?
pub enum QualityOfService {
    Level_0 = 0,
    Level_1 = 1,
    Level_2 = 2,
}

I read the current enum as "level 10" and was puzzled for a bit.
since the last l in level looks a lot like "1".

**Comment by zonyitoo** [comment]
Ah, that would become a breaking change. It is quite distinguishable with my default font:

![image](https://user-images.githubusercontent.com/1067951/117694332-9cc01200-b1f1-11eb-87a0-5159b13c5ad8.png)

**Comment by zonyitoo** [comment]
Yes. `Level_0` doesn't match the Rust's code guideline. So I won't suggest to change it like that.
