### ISSUE TITLE
High level implementation

### ISSUE THREAD

**Issue by kteza1** [zonyitoo/mqtt-rs#6]
I'm implementing higher level functions on top of you library [here](https://github.com/kteza1/amqtt.rs/tree/master/src/client). I intend to push these here eventually if you are OK with it.

**Comment by zonyitoo** [comment]
I think this is a client implementation. Hmm, I would prefer `mqtt-rs` to be a pure protocol library.

**Comment by kteza1** [comment]
Sure. No problem.
